objects/copado__Environment__c.object
<CustomObject>
    <fields>
        <fullName>copado__Platform__c</fullName>
        <defaultValue>&quot;Salesforce&quot;</defaultValue>
        <label>Platform</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                    <default>true</default>
                    <label>Salesforce</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Run_all_tests__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If selected, &quot;Run all local tests&quot; will be enforced when deploying to this environment.</inlineHelpText>
        <label>Run all local tests</label>
        <type>Checkbox</type>
    </fields>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Promotion__c.object
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <fields>
        <fullName>Apex_Test_Level__c</fullName>
        <description>Test levels in order from least to most restrictive</description>
        <label>Apex Test Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Apex_Test_Level</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Destination_Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Destination Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>Promotions (Destination Environment)</relationshipLabel>
        <relationshipName>Promotions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Platform__c</fullName>
        <formula>IF( NOT(ISBLANK( copado__Project__c )) ,  TEXT(copado__Project__r.copado__Deployment_Flow__r.copado__Platform__c) ,  IF( NOT(ISBLANK( copado__Release__c )),  TEXT(copado__Release__r.copado__Project__r.copado__Deployment_Flow__r.copado__Platform__c) , &apos;Salesforce&apos;) )</formula>
        <inlineHelpText>This field auto-populates and displays the pipeline platform.</inlineHelpText>
        <label>Platform</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed with errors</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Validation failed</fullName>
                </value>
                <value>
                    <fullName>Merge Conflict</fullName>
                </value>
                <value>
                    <fullName>Conflicts Resolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Apex_Test_Level.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>No Test Run</fullName>
        <default>true</default>
        <label>No Test Run</label>
    </customValue>
    <customValue>
        <fullName>Run Specified Tests</fullName>
    </customValue>
    <customValue>
        <fullName>Run Local Tests</fullName>
    </customValue>
    <customValue>
        <fullName>Run All Tests In Org</fullName>
    </customValue>
    <customValue>
        <fullName>Run All Tests</fullName>
        <isActive>false</isActive>
        <label>Run All Tests</label>
    </customValue>
    <description>Test levels in order from least to most restrictive</description>
    <masterLabel>Apex Test Level</masterLabel>
</GlobalValueSet>

classes/PromotionsSelector.cls
public with sharing class PromotionsSelector extends fflib_SObjectSelector {
    private Boolean enforceFLS;
    private Boolean enforceCRUD;

    // CONSTRUCTOR

    public PromotionsSelector() {
        this(true, true);
    }

    public PromotionsSelector(Boolean enforceCRUD, Boolean enforceFLS) {
        super(false, enforceCRUD, enforceFLS, false);
        this.enforceFLS = enforceFLS;
        this.enforceCRUD = enforceCRUD;
    }

    // PUBLIC

    public SObjectType getSObjectType() {
        return copado__Promotion__c.sObjectType;
    }

    public List<SObjectField> getSObjectFieldList() {
        return new List<SObjectField>{ copado__Promotion__c.Apex_Test_Level__c };
    }

    public List<copado__Promotion__c> byIdsAndActivePromotedStories(Set<Id> ids) {
        fflib_QueryFactory query = newQueryFactory()
            .selectField('copado__Destination_Environment__r.copado__Run_all_tests__c')
            .setCondition(
                'copado__Platform__c = \'SFDX\' AND Id IN (SELECT copado__Promotion__c from copado__Promoted_User_Story__c WHERE copado__Promotion__c IN :ids AND copado__Status__c = \'Active\')'
            );

        new PromotedUserStoriesSelector(enforceCRUD, enforceFLS)
            .addQueryFactorySubselect(query)
            .selectField('copado__User_Story__r.Apex_Test_Level__c')
            .setCondition(
                'copado__Promotion__r.copado__Destination_Environment__r.copado__Run_all_tests__c = false AND copado__Status__c = \'Active\''
            );

        return Database.query(query.toSOQL());
    }
}