objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Apex_Test_Level__c</fullName>
        <description>Test levels in order from least to most restrictive</description>
        <label>Apex Test Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Apex_Test_Level</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Promotion_Test_Level__c</fullName>
        <description>Test Level to apply in the deployment of the User Story.</description>
        <inlineHelpText>Test Level to apply in the deployment of the User Story.</inlineHelpText>
        <label>Promotion Test Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NoTestRun</fullName>
                    <default>true</default>
                    <label>NoTestRun</label>
                </value>
                <value>
                    <fullName>RunSpecifiedTests</fullName>
                </value>
                <value>
                    <fullName>RunLocalTests</fullName>
                </value>
                <value>
                    <fullName>RunAllTestsInOrg</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__User_Story_Title__c</fullName>
        <description>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</description>
        <inlineHelpText>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</inlineHelpText>
        <label>User Story Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Apex_Test_Level.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>No Test Run</fullName>
        <default>true</default>
        <label>No Test Run</label>
    </customValue>
    <customValue>
        <fullName>Run Specified Tests</fullName>
    </customValue>
    <customValue>
        <fullName>Run Local Tests</fullName>
    </customValue>
    <customValue>
        <fullName>Run All Tests In Org</fullName>
    </customValue>
    <customValue>
        <fullName>Run All Tests</fullName>
        <isActive>false</isActive>
        <label>Run All Tests</label>
    </customValue>
    <description>Test levels in order from least to most restrictive</description>
    <masterLabel>Apex Test Level</masterLabel>
</GlobalValueSet>

classes/SetApexTestLevelTest.cls
@IsTest
private class SetApexTestLevelTest {
    @TestSetup
    private static void makeData() {
        TestUtilities.setup();
        System.runAs(TestUtilities.getRunAsUser()) {
            createData();
        }
    }

    @IsTest
    private static void setEmptyValue() {
        System.runAs(TestUtilities.getRunAsUser()) {
            // Setup

            copado__User_Story__c userStory = getUserStory();
            userStory.copado__Promotion_Test_Level__c = null;

            // Exercise

            Test.startTest();
            update userStory;
            Test.stopTest();

            // Verify

            userStory = getUserStory();
            System.assertEquals(userStory.Apex_Test_Level__c, null, 'Apex_Test_Level__c should be updated to null');
        }
    }

    @IsTest
    private static void setNoRunTest() {
        System.runAs(TestUtilities.getRunAsUser()) {
            // Setup
            
            copado__User_Story__c userStory = getUserStory();
            userStory.copado__Promotion_Test_Level__c = 'NoTestRun';

            // Exercise

            Test.startTest();
            update userStory;
            Test.stopTest();

            // Verify
            
            userStory = getUserStory();
            System.assertEquals(userStory.Apex_Test_Level__c, 'No Test Run', 'Apex_Test_Level__c should be updated to No Test Run');
        }
    }

    @IsTest
    private static void setRunSpecifiedTest() {
        System.runAs(TestUtilities.getRunAsUser()) {
            // Setup
            
            copado__User_Story__c userStory = getUserStory();
            userStory.copado__Promotion_Test_Level__c = 'RunSpecifiedTests';

            // Exercise

            Test.startTest();
            update userStory;
            Test.stopTest();

            // Verify
            
            userStory = getUserStory();
            System.assertEquals(userStory.Apex_Test_Level__c, 'Run Specified Tests', 'Apex_Test_Level__c should be updated to Run Specified Tests');
        }
    }

    @IsTest
    private static void setRunLocalTest() {
        System.runAs(TestUtilities.getRunAsUser()) {
            // Setup
            
            copado__User_Story__c userStory = getUserStory();
            userStory.copado__Promotion_Test_Level__c = 'RunLocalTests';

            // Exercise

            Test.startTest();
            update userStory;
            Test.stopTest();

            // Verify
            
            userStory = getUserStory();
            System.assertEquals(userStory.Apex_Test_Level__c, 'Run Local Tests', 'Apex_Test_Level__c should be updated to Run Local Tests');
        }
    }

    @IsTest
    private static void setRunAllTest() {
        System.runAs(TestUtilities.getRunAsUser()) {
            // Setup
            
            copado__User_Story__c userStory = getUserStory();
            userStory.copado__Promotion_Test_Level__c = 'RunAllTestsInOrg';

            // Exercise

            Test.startTest();
            update userStory;
            Test.stopTest();

            // Verify
            
            userStory = getUserStory();
            System.assertEquals(userStory.Apex_Test_Level__c, 'Run All Tests In Org', 'Apex_Test_Level__c should be updated to Run All Tests In Org');
        }
    }

    private static copado__User_Story__c getUserStory() {
        return [SELECT Id, Apex_Test_Level__c FROM copado__User_Story__c].get(0);
    }

    private static void createData() {
        copado__User_Story__c story = new copado__User_Story__c(copado__User_Story_Title__c = 'US 1', copado__Status__c = 'Draft');
        insert story;
    }
}