objects/copado__JobStep__c.object
<CustomObject>
    <fields>
        <fullName>copado__ConfigJson__c</fullName>
        <label>ConfigJson</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>copado__CustomType__c</fullName>
        <description>Defines the type of configuration required for this step.</description>
        <inlineHelpText>Defines the type of configuration required for this step.</inlineHelpText>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__ExecutionSequence__c</fullName>
        <description>Used to define the order of execution in the context of User Story Deployment</description>
        <label>Execution Sequence</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>before</fullName>
                    <label>Before Deployment</label>
                </value>
                <value>
                    <fullName>after</fullName>
                    <label>After Deployment</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Order__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>copado__Type__c</fullName>
        <description>Defines the behaviour this step will have when executed.</description>
        <inlineHelpText>Defines the behaviour this step will have when executed.</inlineHelpText>
        <label>Behaviour</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Function</fullName>
                </value>
                <value>
                    <fullName>Flow</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__UserStory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>copado__User_Story__c</referenceTo>
        <relationshipLabel>Deployment Steps</relationshipLabel>
        <relationshipName>JobSteps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>copado__Order__c</fullName>
        <label>Order</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ConfigurePipelineDistributionStep.cls
public with sharing class ConfigurePipelineDistributionStep {
    private Request request;
    private Id userStoryId;

    // CTOR

    public ConfigurePipelineDistributionStep(Request request) {
        this.request = request;
    }

    // PUBLIC

    @InvocableMethod(label='Create deployment step for user story' category='Package Distribution')
    public static List<Result> createDeploymentStep(List<Request> requests) {
        Result result = new Result();

        result.userStoryId = new ConfigurePipelineDistributionStep(requests[0]).execute();

        return new List<Result>{ result };
    }


    public Id execute() {
        userStoryId = String.isBlank(request.existingUserStoryId) ? createUserStory() : request.existingUserStoryId;

        createDeploymentStep();

        return userStoryId;
    }

    // PRIVATE

    @SuppressWarnings('PMD.ApexCRUDViolation')
    private Id createUserStory() {
        copado__User_Story__c userStory = (copado__User_Story__c) JSON.deserialize(
            request.newSerializedUserStory,
            copado__User_Story__c.class
        );

        userStory = (copado__User_Story__c) Security.stripInaccessible(
                AccessType.CREATABLE,
                new List<copado__User_Story__c>{ userStory }
            )
            .getRecords()
            .get(0);

        insert userStory;
        return userStory.Id;
    }


    private void createDeploymentStep() {
        copado__JobStep__c step = new copado__JobStep__c(
            Name = getStepName(),
            copado__UserStory__c = userStoryId,
            copado__Type__c = 'Flow',
            copado__CustomType__c = 'Flow',
            copado__ExecutionSequence__c = 'after',
            copado__Order__c = getStepOrder(),
            copado__ConfigJson__c = getConfigJson()
        );

        insert Security.stripInaccessible(AccessType.CREATABLE, new List<SObject>{ step }).getRecords();
    }


    private String getConfigJson() {
        ConfigJson configJson = new ConfigJson(Settings.NAMESPACE_DOT + 'InitiatePipelineDistribution');
        configJson.parameters = new List<Parameter>{
            new Parameter('packageVersionId', request.packageVersionId),
            // Note: This is deployment job execution
            new Parameter('deploymentId', '{$Job.ExecutionParent.Id}')
        };

        return JSON.serialize(configJson);
    }


    private String getStepName() {
        copado__Artifact_Version__c packageVersion = new PackageVersionsSelector()
            .byIds(new Set<Id>{ request.packageVersionId })
            .get(0);

        return 'Start ' +
            packageVersion.copado__Artifact__r.Name +
            ' - ' +
            packageVersion.copado__Version_number__c +
            ' Installation Job';
    }


    private Decimal getStepOrder() {
        Decimal maxOrder = (Decimal) [
                SELECT MAX(copado__Order__c) MaxOrder
                FROM copado__JobStep__c
                WHERE copado__UserStory__c = :userStoryId AND copado__ExecutionSequence__c = 'after'
            ]
            .get(0)
            .get('MaxOrder');

        return (maxOrder == null) ? 1 : (maxOrder + 1);
    }

    // INNER PUBLIC

    public class Request {
        @InvocableVariable(label='Existing User Story Id')
        public String existingUserStoryId;

        @InvocableVariable(label='New Serialized User Story')
        public String newSerializedUserStory;

        @InvocableVariable(label='Package Version Id' required=true)
        public String packageVersionId;
    }


    public class Result {
        @InvocableVariable(label='User Story Id')
        public String userStoryId;
    }

    // INNER PRIVATE

    @TestVisible
    private class ConfigJson {
        @TestVisible
        private String flowName;

        @TestVisible
        private List<Parameter> parameters;

        // CTOR

        private ConfigJson(String flowName) {
            this.flowName = flowName;
        }
    }
    

    @TestVisible
    private class Parameter {
        @TestVisible
        private String name;

        @TestVisible
        private String value;

        // CTOR
        
        @TestVisible
        private Parameter(String name, String value) {
            this.name = name;
            this.value = value;
        }
    }
}