objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__User_Story_Metadata__c.object
<CustomObject>
    <fields>
        <fullName>copado__Action__c</fullName>
        <description>Action to be performed with the current metadata when committing</description>
        <inlineHelpText>Action to be performed with the current metadata when committing</inlineHelpText>
        <label>Action</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Type__c</fullName>
        <description>Type of the metadata</description>
        <inlineHelpText>Type of the metadata</inlineHelpText>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>copado__User_Story__c</referenceTo>
        <relationshipLabel>User Story Metadata</relationshipLabel>
        <relationshipName>User_Story_Metadata</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story Metadata</label>
    <nameField>
        <label>User Story Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Metadata</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UserStoryMetadataSelector.cls
public with sharing class UserStoryMetadataSelector extends fflib_SObjectSelector {
    // CONSTRUCTOR

    public UserStoryMetadataSelector() {
        this(true, true);
    }

    public UserStoryMetadataSelector(Boolean enforceCRUD, Boolean enforceFLS) {
        super(false, enforceCRUD, enforceFLS, false);
    }

    // PUBLIC

    public SObjectType getSObjectType() {
        return copado__User_Story_Metadata__c.sObjectType;
    }

    public List<SObjectField> getSObjectFieldList() {
        return new List<SObjectField>{ copado__User_Story_Metadata__c.copado__User_Story__c, copado__User_Story_Metadata__c.copado__Type__c };
    }

    public List<copado__User_Story_Metadata__c> byStoryIdsAndActionAddOrFull(Set<Id> ids) {
        return Database.query(
            newQueryFactory()
                .setCondition(copado__User_Story_Metadata__c.copado__User_Story__c + ' IN :ids AND copado__Action__c IN (\'Add\',\'Full\')')
                .toSOQL()
        );
    }
}