objects/copado__Deployment__c.object
<CustomObject>
    <fields>
        <fullName>copado__Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion</label>
        <referenceTo>copado__Promotion__c</referenceTo>
        <relationshipLabel>Deployments</relationshipLabel>
        <relationshipName>Deployments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/copado__Promotion__c.object
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <fields>
        <fullName>copado__Destination_Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The destination credential that will be used when creating the deployment. This credential is auto-populated based on the pipeline linked to the project.</inlineHelpText>
        <label>Destination Credential</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>copado__Org__c.copado__Environment__c</field>
                <operation>equals</operation>
                <valueField>$Source.copado__Destination_Environment__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>Promotions (Destination Credential)</relationshipLabel>
        <relationshipName>Promotions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/InitiatePipelineDistribution.cls
public with sharing class InitiatePipelineDistribution {
    
    // PUBLIC

    @InvocableMethod(label='Executes Package Distribution Job' category='Package Distribution')
    public static List<Result> startExecution(List<Request> requests) {
        System.debug(requests);
        Result result = new Result();

        copado__Deployment__c deployment = new DeploymentsSelector()
            .byIds(new Set<Id>{ requests[0].deploymentId })
            .get(0);

        Id destinationCredential = deployment.copado__Promotion__r.copado__Destination_Org_Credential__c;

        result.job = new DeployPackages(requests[0].packageVersionId, new List<Id>{ destinationCredential })
            .execute()
            .get(0);

            System.debug(new List<Result>{ result });
        return new List<Result>{ result };
    }

    // INNER

    public class Request {
        @InvocableVariable(label='Package Version Id' required=true)
        public String packageVersionId;

        @InvocableVariable(label='Deployment Id' required=true)
        public String deploymentId;
    }


    public class Result {
        @InvocableVariable(label='Job Execution')
        public copado__JobExecution__c job;
    }
}