objects/copado__JobStep__c.object
<CustomObject>
    <fields>
        <fullName>copado__JobExecution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Job Execution</label>
        <referenceTo>copado__JobExecution__c</referenceTo>
        <relationshipLabel>Job Steps</relationshipLabel>
        <relationshipName>JobSteps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Promotion__c.object
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JobStepsSelector.cls
public with sharing class JobStepsSelector extends fflib_SObjectSelector {
    // CONSTRUCTOR

    public JobStepsSelector() {
        this(true, true);
    }

    public JobStepsSelector(Boolean enforceCRUD, Boolean enforceFLS) {
        super(false, enforceCRUD, enforceFLS, false);
    }

    // PUBLIC

    public SObjectType getSObjectType() {
        return copado__JobStep__c.sObjectType;
    }

    public List<SObjectField> getSObjectFieldList() {
        return new List<SObjectField>{ copado__JobStep__c.Name };
    }

    public List<copado__JobStep__c> promotionByIds(Set<Id> ids) {
        return Database.query(
            newQueryFactory()
                .selectField('copado__JobExecution__r.copado__Deployment__r.copado__Promotion__c')
                .setCondition(copado__JobStep__c.Id + ' IN :ids')
                .toSOQL()
        );
    }
}