objects/copado__Environment__c.object
<CustomObject>
    <fields>
        <fullName>copado__Run_all_tests__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If selected, &quot;Run all local tests&quot; will be enforced when deploying to this environment.</inlineHelpText>
        <label>Run all local tests</label>
        <type>Checkbox</type>
    </fields>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Promotion__c.object
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <fields>
        <fullName>Apex_Test_Level__c</fullName>
        <description>Test levels in order from least to most restrictive</description>
        <label>Apex Test Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Apex_Test_Level</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Destination_Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Destination Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>Promotions (Destination Environment)</relationshipLabel>
        <relationshipName>Promotions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Apex_Test_Level.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>No Test Run</fullName>
        <default>true</default>
        <label>No Test Run</label>
    </customValue>
    <customValue>
        <fullName>Run Specified Tests</fullName>
    </customValue>
    <customValue>
        <fullName>Run Local Tests</fullName>
    </customValue>
    <customValue>
        <fullName>Run All Tests In Org</fullName>
    </customValue>
    <customValue>
        <fullName>Run All Tests</fullName>
        <isActive>false</isActive>
        <label>Run All Tests</label>
    </customValue>
    <description>Test levels in order from least to most restrictive</description>
    <masterLabel>Apex Test Level</masterLabel>
</GlobalValueSet>

classes/UpdatePromotionTestLevel.cls
public with sharing class UpdatePromotionTestLevel {
    private Set<Id> promotionIds;
    @TestVisible
    private static final List<String> TEST_LEVELS_IN_ORDER = Utilities.getPicklistValues(
        SObjectType.copado__Promotion__c.getName(),
        copado__Promotion__c.Apex_Test_Level__c.getDescribe().getName()
    );

    private Integer lastTestLevelIndex {
        get {
            return TEST_LEVELS_IN_ORDER.size() - 1;
        }
    }

    private Boolean enforceCRUDFLS = !Trigger.isExecuting;

    // CONSTRUCTOR

    public UpdatePromotionTestLevel(List<copado__Promoted_User_Story__c> promotedStories) {
        this.promotionIds = getPromotionIds(promotedStories);
    }

    public UpdatePromotionTestLevel(Set<Id> promotionIds) {
        this.promotionIds = promotionIds;
    }

    // PUBLIC

    public void execute() {
        try {
            List<copado__Promotion__c> promotionsToUpdate = new List<copado__Promotion__c>();

            for (
                copado__Promotion__c promotion : new PromotionsSelector(enforceCRUDFLS, enforceCRUDFLS)
                    .byIdsAndActivePromotedStories(promotionIds)
            ) {
                String newTestLevel;

                if (promotion.copado__Destination_Environment__r.copado__Run_all_tests__c) {
                    newTestLevel = TEST_LEVELS_IN_ORDER.get(lastTestLevelIndex);
                } else {
                    newTestLevel = calculateTestLevel(promotion.copado__Promoted_User_Stories__r);
                }

                if (newTestLevel != promotion.Apex_Test_Level__c) {
                    promotion.Apex_Test_Level__c = newTestLevel;
                    promotionsToUpdate.add(promotion);
                }
            }

            update Security.stripInaccessible(AccessType.UPDATABLE, promotionsToUpdate, true).getRecords();
        } catch (Exception ex) {
            throw new ApplicationException(ex.getMessage());
        }
    }

    // PRIVATE

    private Set<Id> getPromotionIds(List<copado__Promoted_User_Story__c> promotedStories) {
        Set<Id> promotionIds = new Set<Id>();

        for (copado__Promoted_User_Story__c ps : promotedStories) {
            promotionIds.add(ps.copado__Promotion__c);
        }

        return promotionIds;
    }

    private String calculateTestLevel(List<copado__Promoted_User_Story__c> promotedStories) {
        Integer currIndex = 0;

        for (copado__Promoted_User_Story__c ps : promotedStories) {
            Integer newIndex = TEST_LEVELS_IN_ORDER.indexOf(ps.copado__User_Story__r.Apex_Test_Level__c);
            currIndex = (newIndex > currIndex) ? newIndex : currIndex;

            if (currIndex == lastTestLevelIndex) {
                break;
            }
        }

        return TEST_LEVELS_IN_ORDER.get(currIndex);
    }
}