objects/copado__Artifact__c.object
<CustomObject>
    <fields>
        <fullName>copado__Artifact_Repository__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is Repository where the Artifact can be stored, in the master branch</inlineHelpText>
        <label>Package Repository</label>
        <referenceTo>copado__Git_Repository__c</referenceTo>
        <relationshipLabel>Packages</relationshipLabel>
        <relationshipName>Artifacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Artifact_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest Package Version</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>copado__Artifact_Version__c.copado__Artifact__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>copado__Artifact_Version__c</referenceTo>
        <relationshipName>Artifacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Description__c</fullName>
        <inlineHelpText>The description of the package</inlineHelpText>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>copado__Package_Id__c</fullName>
        <inlineHelpText>Related package identifier. Being used as a Package Id for package version creation and also in use into the sfdx-project.json file as a package alias.</inlineHelpText>
        <label>Package Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Package_Type__c</fullName>
        <inlineHelpText>For detailed information : https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_dev2gp_plan_pkg_types.htm</inlineHelpText>
        <label>Package Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unlocked</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Second-Generation Package</fullName>
                </value>
                <value>
                    <fullName>First-Generation Package</fullName>
                </value>
                <value>
                    <fullName>Unmanaged</fullName>
                    <isActive>false</isActive>
                    <label>Unmanaged</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Deployment_Flow__c.object
<CustomObject>
    <fields>
        <fullName>copado__Git_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>copado__Git_Repository__c</referenceTo>
        <relationshipName>Deployment_Flows</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Platform__c</fullName>
        <label>Platform</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                    <default>true</default>
                    <label>Salesforce</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>SFDX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreatePackageFlowTest.cls
@IsTest
private class CreatePackageFlowTest {
    @SuppressWarnings('PMD.AvoidHardcodingId')
    private static final String SUBSCRIBER_ID = '04t09000000G3icAAC';

    @TestSetup
    private static void setUp() {
        TestUtilities.setup();
    }

    @IsTest
    private static void insertPackageAndVersion() {
        // Setup
        System.runAs(TestUtilities.getRunAsUser()) {
            Map<String, Object> flowParams = getFlowParams(createPipeline(createRepository().Id));

            // Exercise
            Test.startTest();
            new Flow.Interview.Create_Package(flowParams).start();
            Test.stopTest();
            // Verify
            List<copado__Artifact__c> packages = getPackages();

            System.assertEquals(packages.size(), 1, 'Package upsertion failed');
            System.assertEquals(
                packages.get(0).copado__Artifact_Versions__r.size(),
                1,
                'Package version upsertion failed'
            );
        }
    }

    @IsTest
    private static void updatePackageAndVersion() {
        // Setup
        System.runAs(TestUtilities.getRunAsUser()) {
            copado__Git_Repository__c repo = createRepository();

            copado__Artifact__c pkg = createPackage(repo);
            createPackageVersion(repo, pkg);

            Map<String, Object> flowParams = getFlowParams(createPipeline(repo.Id));

            PackageInfo info = PackageInfo.parse(String.valueOf(flowParams.get('packageJson')));
            info.pkg.Description = 'Package Description';
            info.versions.get(0).Description = 'Package Version Description';
            flowParams.put('packageJson', JSON.serialize(info));
            // Exercise
            Test.startTest();
            new Flow.Interview.Create_Package(flowParams).start();
            Test.stopTest();

            // Verify
            List<copado__Artifact__c> packages = getPackages();

            System.assertEquals(
                packages.get(0).copado__Description__c,
                'Package Description',
                'Package upsert description failed'
            );
            System.assertEquals(
                packages.get(0).copado__Artifact_Versions__r.get(0).copado__Version_Description__c,
                'Package Version Description',
                'Package version upsert description failed'
            );
        }
    }

    @IsTest
    private static void throwException() {
        // Setup
        System.runAs(TestUtilities.getRunAsUser()) {
            Map<String, Object> flowParams = getFlowParams(createPipeline(createRepository().Id));

            flowParams.put('jsonInformation', '{"devhub":"invalidId"}');
            // Exercise
            Test.startTest();
            new Flow.Interview.Create_Package(flowParams).start();
            Test.stopTest();

            // Verify
            List<copado__Artifact__c> packages = getPackages();

            System.assertEquals(packages.size(), 0, 'throw exception failed');
        }
    }

    private static copado__Deployment_Flow__c createPipeline(Id repositoryId) {
        copado__Deployment_Flow__c pipeline = new copado__Deployment_Flow__c(
            Name = 'My Pipeline',
            copado__Platform__c = 'Salesforce',
            copado__Git_Repository__c = repositoryId
        );
        insert pipeline;
        return pipeline;
    }
    private static copado__Git_Repository__c createRepository() {
        copado__Git_Repository__c repo = new copado__Git_Repository__c(Name = 'My Repo');
        insert repo;
        return repo;
    }
    private static Map<String, Object> getFlowParams(copado__Deployment_Flow__c pipeline) {
        Map<String, Object> flowParams = new Map<String, Object>{
            'packageJson' => '{"pkg":{"Id":"0Ho5g00000000VzCAI","SubscriberPackageId":"0335g000000xW5pAAE","Name":"Testpkg","Description":null,"NamespacePrefix":null,"ContainerOptions":"Unlocked","Alias":""},"versions":[{"Package2Id":"0Ho5g00000000VzCAI","Branch":null,"Tag":null,"MajorVersion":0,"MinorVersion":1,"PatchVersion":0,"BuildNumber":1,"Id":"05i5g00000000OcAAI","SubscriberPackageVersionId":"04t5g000000xwXMAAY","Name":"ver 0.1","NamespacePrefix":null,"Package2Name":"Testpkg","Description":null,"Version":"0.1.0.1","IsPasswordProtected":false,"IsReleased":false,"CreatedDate":"2021-09-01 11:42","LastModifiedDate":"2021-09-01 11:42","InstallUrl":"https://login.salesforce.com/packaging/installPackage.apexp?p0=04t5g000000xwXMAAY","CodeCoverage":"","ValidationSkipped":false,"AncestorId":"N/A","AncestorVersion":"N/A","Alias":""}]}',
            'pipelineId' => pipeline.Id
        };
        return flowParams;
    }

    @SuppressWarnings('PMD.AvoidHardcodingId')
    private static copado__Artifact__c createPackage(Copado__Git_Repository__c repo) {
        copado__Artifact__c pkg = new copado__Artifact__c();
        pkg.Name = 'Testpkg';
        pkg.copado__Package_Type__c = 'Unlocked';
        pkg.copado__Artifact_Repository__c = repo.Id;
        pkg.copado__Package_Id__c = '0Ho5g00000000VzCAI';
        pkg.RecordTypeId = SObjectType.copado__Artifact__c.getRecordTypeInfosByDeveloperName()
            .get('Package_Artifact')
            .getRecordTypeId();

        insert pkg;
        return pkg;
    }

    private static void createPackageVersion(
        Copado__Git_Repository__c repo,
        copado__Artifact__c pkg
    ) {
        copado__Artifact_Version__c version = new copado__Artifact_Version__c();
        version.copado__Artifact__c = pkg.Id;
        version.Name = 'ver 0.1';
        version.copado__Version_number__c = '0.1.0.1';
        version.copado__Subscriber_Version_Id__c = SUBSCRIBER_ID;

        insert version;
    }

    private static List<copado__Artifact__c> getPackages() {
        return [
            SELECT
                copado__Description__c,
                (
                    SELECT copado__Version_number__c, copado__Version_Description__c
                    FROM copado__Artifact_Versions__r
                )
            FROM copado__Artifact__c
        ];
    }
}