objects/copado__Deployment__c.object
<CustomObject>
    <fields>
        <fullName>copado__From_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Credential</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>copado__Org__c.CreatedById</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>Deployments (From Credential)</relationshipLabel>
        <relationshipName>Deployments_From_Org</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Git_Repository__c</fullName>
        <formula>IF(NOT(ISBLANK(copado__Promotion__r.copado__Project__c)), copado__Promotion__r.copado__Project__r.copado__Deployment_Flow__r.copado__Git_Repository__c,  copado__Promotion__r.copado__Release__r.copado__Project__r.copado__Deployment_Flow__r.copado__Git_Repository__c )</formula>
        <label>Git Repository</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion</label>
        <referenceTo>copado__Promotion__c</referenceTo>
        <relationshipLabel>Deployments</relationshipLabel>
        <relationshipName>Deployments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Source_Environment__c</fullName>
        <formula>copado__From_Org__r.copado__Environment__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Source Environment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The automation template that defined the steps of this deployment.</inlineHelpText>
        <label>Template</label>
        <referenceTo>copado__Deployment__c</referenceTo>
        <relationshipLabel>Template Execution</relationshipLabel>
        <relationshipName>Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/copado__Deployment_Flow__c.object
<CustomObject>
    <fields>
        <fullName>copado__Git_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>copado__Git_Repository__c</referenceTo>
        <relationshipName>Deployment_Flows</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Platform__c</fullName>
        <label>Platform</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                    <default>true</default>
                    <label>Salesforce</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>SFDX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Promotion_Job_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion Job Template</label>
        <referenceTo>copado__JobTemplate__c</referenceTo>
        <relationshipLabel>Pipelines</relationshipLabel>
        <relationshipName>Pipelines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Environment__c.object
<CustomObject>
    <fields>
        <fullName>copado__Platform__c</fullName>
        <defaultValue>&quot;Salesforce&quot;</defaultValue>
        <label>Platform</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                    <default>true</default>
                    <label>Salesforce</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__JobStep__c.object
<CustomObject>
    <fields>
        <fullName>copado__Git_Repository__c</fullName>
        <formula>BLANKVALUE(
    copado__JobExecution__r.copado__Snapshot__r.copado__Git_Repository__c, 
    BLANKVALUE(
        copado__JobExecution__r.copado__Pipeline__r.copado__Git_Repository__c,
        BLANKVALUE(
            copado__JobExecution__r.copado__Promotion__r.copado__Project__r.copado__Deployment_Flow__r.copado__Git_Repository__c, 
            copado__JobExecution__r.copado__Deployment__r.copado__Promotion__r.copado__Project__r.copado__Deployment_Flow__r.copado__Git_Repository__c
        )
    )
)</formula>
        <label>Git Repository</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__JobExecution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Job Execution</label>
        <referenceTo>copado__JobExecution__c</referenceTo>
        <relationshipLabel>Job Steps</relationshipLabel>
        <relationshipName>JobSteps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__JobTemplate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Job Template</label>
        <referenceTo>copado__JobTemplate__c</referenceTo>
        <relationshipLabel>Job Steps</relationshipLabel>
        <relationshipName>JobSteps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Type__c</fullName>
        <description>Defines the behaviour this step will have when executed.</description>
        <inlineHelpText>Defines the behaviour this step will have when executed.</inlineHelpText>
        <label>Behaviour</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Function</fullName>
                </value>
                <value>
                    <fullName>Flow</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Promotion__c.object
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <fields>
        <fullName>copado__Platform__c</fullName>
        <formula>IF( NOT(ISBLANK( copado__Project__c )) ,  TEXT(copado__Project__r.copado__Deployment_Flow__r.copado__Platform__c) ,  IF( NOT(ISBLANK( copado__Release__c )),  TEXT(copado__Release__r.copado__Project__r.copado__Deployment_Flow__r.copado__Platform__c) , &apos;Salesforce&apos;) )</formula>
        <inlineHelpText>This field auto-populates and displays the pipeline platform.</inlineHelpText>
        <label>Platform</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select a project linked to an active pipeline.</inlineHelpText>
        <label>Project</label>
        <referenceTo>copado__Project__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Source_Environment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Source Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Source_Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The source credential that will be used when creating the deployment. This credential is auto-populated based on the pipeline linked to the project.</inlineHelpText>
        <label>Source Credential</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>copado__Org__c.copado__Environment__c</field>
                <operation>equals</operation>
                <valueField>$Source.copado__Source_Environment__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>Promotions (Source Credential)</relationshipLabel>
        <relationshipName>Promotions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>copado__Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Credential.</description>
        <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Credential.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Git_Repository__c</fullName>
        <formula>copado__Project__r.copado__Deployment_Flow__r.copado__Git_Repository__c</formula>
        <label>Git Repository</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</description>
        <inlineHelpText>Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</inlineHelpText>
        <label>Credential</label>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>User Stories (Credential)</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Platform__c</fullName>
        <description>This field auto-populates and displays the pipeline platform</description>
        <formula>BLANKVALUE( 
    TEXT(copado__Project__r.copado__Deployment_Flow__r.copado__Platform__c) ,  
    BLANKVALUE(  
        TEXT(copado__Release__r.copado__Project__r.copado__Deployment_Flow__r.copado__Platform__c), 
        &apos;&apos;
    ) 
)</formula>
        <inlineHelpText>This field auto-populates and displays the pipeline platform</inlineHelpText>
        <label>Platform</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project where the User Story belongs.</description>
        <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
        <label>Project</label>
        <referenceTo>copado__Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__User_Story_Title__c</fullName>
        <description>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</description>
        <inlineHelpText>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</inlineHelpText>
        <label>User Story Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GetTestOnlyClassesTest.cls
@IsTest
private class GetTestOnlyClassesTest {
    @TestSetup
    private static void setUp() {
        TestUtilities.setup();
        System.runAs(TestUtilities.getRunAsUser()) {
            makeData();
        }
    }

    @IsTest
    private static void testGetTestOnlyClasses() {
        // SETUP

        System.runAs(TestUtilities.getRunAsUser()) {
            // EXERCISE
            copado__JobStep__c jobStep = [SELECT Id FROM copado__JobStep__c LIMIT 1];
            String testClasses = new GetTestOnlyClasses().execute(jobStep.Id);

            // VERIFY
            Set<String> assertNames = getAssertNames();
            Set<String> assertTestClassNames = (Set<String>) JSON.deserialize(testClasses, Set<String>.class);

            System.assertEquals(assertNames, assertTestClassNames, 'Class names does not match');
        }
    }

    // HELPER

    private static void makeData() {
        copado__Git_Repository__c repository = TestDataFactory.createGitRepository('MyRepo');
        insert repository;

        copado__Environment__c devEnvironment = TestDataFactory.createEnvironment('Dev1', 'Production/Developer', 'SFDX');
        copado__Environment__c uatEnvironment = TestDataFactory.createEnvironment('Uat', 'Production/Developer', 'SFDX');
        insert new List<copado__Environment__c>{ devEnvironment, uatEnvironment };

        copado__Org__c devCredential = TestDataFactory.createCredential('Dev1', 'name@example.com', devEnvironment.Id, 'Production/Developer');
        copado__Org__c uatCredential = TestDataFactory.createCredential('Uat', 'nameuat@example.com', uatEnvironment.Id, 'Production/Developer');
        insert new List<copado__Org__c>{ devCredential, uatCredential };

        copado__JobTemplate__c jobTemplate = TestDataFactory.createJobTemplate('Promotion');
        insert jobTemplate;

        copado__Deployment_Flow__c pipeline = TestDataFactory.createPipeline('MyPipeline', repository.Id);
        pipeline.copado__Platform__c = 'SFDX';
        pipeline.copado__Promotion_Job_Template__c = jobTemplate.Id;
        insert pipeline;

        copado__Deployment_Flow_Step__c connection = TestDataFactory.createPipelineConnection(pipeline.Id, devEnvironment.Id, uatEnvironment.Id);
        insert connection;

        copado__Project__c project = TestDataFactory.createProject('MyProject', pipeline.Id);
        insert project;

        copado__User_Story__c story1 = new copado__User_Story__c(
            copado__User_Story_Title__c = 'My Story One',
            copado__Project__c = project.Id,
            copado__Org_Credential__c = devCredential.Id
        );
        copado__User_Story__c story2 = new copado__User_Story__c(
            copado__User_Story_Title__c = 'My Story Two',
            copado__Project__c = project.Id,
            copado__Org_Credential__c = devCredential.Id
        );
        insert new List<copado__User_Story__c>{ story1, story2 };

        Attachment attachment1 = new Attachment(ParentId = story1.Id, Name = 'Test Classes', Body = Blob.valueOf(mockTestClasses()));
        Attachment attachment2 = new Attachment(ParentId = story1.Id, Name = 'Test Classes.json', Body = Blob.valueOf(mockTestClasses()));
        Attachment attachment3 = new Attachment(ParentId = story1.Id, Name = 'cmcSf_TestClasses.json', Body = Blob.valueOf(mockTestClasses()));
        insert new List<Attachment>{ attachment1, attachment2, attachment3 };

        ContentVersion content = new ContentVersion(
            Title = 'cmcSf_TestClasses',
            origin = 'C',
            PathOnClient = 'cmcSf_TestClasses.json',
            VersionData = Blob.valueOf(mockTestClasses2())
        );
        insert content;

        ContentVersion contentVersion = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :content.Id LIMIT 1];

        ContentDocumentLink link = new ContentDocumentLink(LinkedEntityId = story2.Id, ContentDocumentId = contentVersion.ContentDocumentId);
        insert link;

        copado__Promotion__c promotion = new copado__Promotion__c(
            copado__Project__c = project.Id,
            copado__Source_Org_Credential__c = devCredential.Id,
            copado__Source_Environment__c = devEnvironment.Id
        );
        insert promotion;

        copado__Promoted_User_Story__c promotedstory1 = new copado__Promoted_User_Story__c(
            copado__Promotion__c = promotion.Id,
            copado__User_Story__c = story1.Id
        );
        copado__Promoted_User_Story__c promotedstory2 = new copado__Promoted_User_Story__c(
            copado__Promotion__c = promotion.Id,
            copado__User_Story__c = story2.Id
        );
        insert new List<copado__Promoted_User_Story__c>{ promotedstory1, promotedstory2 };

        copado__Deployment__c deployment = new copado__Deployment__c(
            Name = promotion.Name,
            copado__Promotion__c = promotion.Id,
            copado__From_Org__c = devCredential.Id
        );
        insert deployment;

        copado__JobExecution__c execution = new copado__JobExecution__c(
            copado__Deployment__c = deployment.Id,
            copado__Promotion__c = promotion.Id,
            copado__Template__c = jobTemplate.Id,
            copado__Source__c = devEnvironment.Id,
            copado__Destination__c = uatEnvironment.Id
        );
        insert execution;

        copado__JobStep__c step = new copado__JobStep__c(copado__JobExecution__c = execution.Id, copado__Type__c = 'Function');
        insert step;
    }

    private static String mockTestClasses() {
        List<MetaDataItem> metadataItems = new List<MetaDataItem>();
        MetaDataItem item1 = new MetaDataItem();
        item1.n = 'My Test class one';
        item1.r = false;
        item1.s = true;

        MetaDataItem item2 = new MetaDataItem();
        item2.n = 'My Test class two';
        item2.r = false;
        item2.s = true;

        metadataItems.add(item1);
        metadataItems.add(item2);

        return JSON.serialize(metadataItems);
    }

    private static String mockTestClasses2() {
        List<MetaDataItem> metadataItems = new List<MetaDataItem>();
        MetaDataItem item1 = new MetaDataItem();
        item1.n = 'My Test class four';
        item1.r = false;
        item1.s = true;

        MetaDataItem item2 = new MetaDataItem();
        item2.n = 'My Test class Five';
        item2.r = false;
        item2.s = true;

        metadataItems.add(item1);
        metadataItems.add(item2);

        return JSON.serialize(metadataItems);
    }

    private static Set<String> getAssertNames() {
        Set<String> result = new Set<String>();

        for (MetaDataItem item : (List<MetaDataItem>) JSON.deserialize(mockTestClasses(), List<MetaDataItem>.class)) {
            result.add(item.n + '.cls');
        }

        for (MetaDataItem item : (List<MetaDataItem>) JSON.deserialize(mockTestClasses2(), List<MetaDataItem>.class)) {
            result.add(item.n + '.cls');
        }

        return result;
    }
}