objects/copado__Artifact__c.object
<CustomObject>
    <fields>
        <fullName>copado__Artifact_Repository__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is Repository where the Artifact can be stored, in the master branch</inlineHelpText>
        <label>Package Repository</label>
        <referenceTo>copado__Git_Repository__c</referenceTo>
        <relationshipLabel>Packages</relationshipLabel>
        <relationshipName>Artifacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Package_Type__c</fullName>
        <inlineHelpText>For detailed information : https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_dev2gp_plan_pkg_types.htm</inlineHelpText>
        <label>Package Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unlocked</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Second-Generation Package</fullName>
                </value>
                <value>
                    <fullName>First-Generation Package</fullName>
                </value>
                <value>
                    <fullName>Unmanaged</fullName>
                    <isActive>false</isActive>
                    <label>Unmanaged</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Pipeline__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pipeline</label>
        <referenceTo>copado__Deployment_Flow__c</referenceTo>
        <relationshipLabel>Packages</relationshipLabel>
        <relationshipName>Packages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Target_Dev_Hub_Org__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Copado org credential for the dev hub which will be used to create and store the package and its versions</inlineHelpText>
        <label>Target Dev Hub Org</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only dev hub org credentials can be selected. Given value not found or it is not a dev hub org.</errorMessage>
            <filterItems>
                <field>copado__Org__c.copado__is_Developer_Hub_Org__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipName>packageArtifacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Deployment_Flow__c.object
<CustomObject>
    <fields>
        <fullName>copado__Git_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>copado__Git_Repository__c</referenceTo>
        <relationshipName>Deployment_Flows</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Platform__c</fullName>
        <label>Platform</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                    <default>true</default>
                    <label>Salesforce</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>SFDX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Environment__c.object
<CustomObject>
    <fields>
        <fullName>copado__Platform__c</fullName>
        <defaultValue>&quot;Salesforce&quot;</defaultValue>
        <label>Platform</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                    <default>true</default>
                    <label>Salesforce</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PackageCreateHandlerTest.cls
@IsTest
private class PackageCreateHandlerTest {
    @TestSetup
    private static void setUp() {
        TestUtilities.setup();
        
        System.runAs(TestUtilities.getRunAsUser()) {
            
            copado__Environment__c environment = TestDataFactory.createEnvironment(
                'DevHub',
                'Production/Developer',
                'SFDX'
            );
            insert environment;

            copado__Org__c credential = TestDataFactory.createCredential(
                'DevHub',
                'test@test.com',
                environment.Id,
                'Production/Developer'
            );
            credential.copado__is_Developer_Hub_Org__c = true;
            insert credential;

            copado__JobTemplate__c template = TestDataFactory.createJobTemplate(
                'SFDX Package Create'
            );
            insert template;

            copado__Git_Repository__c repo = createRepository();

            createPackage(repo, createPipeline(repo.Id).Id, credential.Id);
        }
    }

    @IsTest
    private static void generatePackage() {
        // Setup

        System.runAs(TestUtilities.getRunAsUser()) {
            // Exercise

            Test.startTest();
            PackageCreateHandler.startCreate(getPackage()[0].Id);
            Test.stopTest();

            // Verify

            System.assertEquals(getJobExecution().size(), 1, 'Package generation failed');
        }
    }

    private static copado__Git_Repository__c createRepository() {
        copado__Git_Repository__c repo = new copado__Git_Repository__c(Name = 'My Repo');
        insert repo;
        return repo;
    }

    private static copado__Artifact__c createPackage(
        Copado__Git_Repository__c repo,
        Id pipelineId,
        Id credentialId
    ) {
        copado__Artifact__c pkg = new copado__Artifact__c();
        pkg.Name = 'Testpkg';
        pkg.copado__Package_Type__c = 'Unlocked';
        pkg.copado__Artifact_Repository__c = repo.Id;
        pkg.copado__Pipeline__c = pipelineId;
        pkg.copado__Target_Dev_Hub_Org__c = credentialId;
        pkg.RecordTypeId = SObjectType.copado__Artifact__c.getRecordTypeInfosByDeveloperName()
            .get('Package_Artifact')
            .getRecordTypeId();

        insert pkg;
        return pkg;
    }

    private static copado__Deployment_Flow__c createPipeline(Id repositoryId) {
        copado__Deployment_Flow__c pipeline = new copado__Deployment_Flow__c(
            Name = 'My Pipeline',
            copado__Platform__c = 'SFDX',
            copado__Git_Repository__c = repositoryId
        );
        insert pipeline;
        return pipeline;
    }

    private static List<copado__Artifact__c> getPackage() {
        return [SELECT Id FROM copado__Artifact__c];
    }

    private static List<copado__JobExecution__c> getJobExecution() {
        return [SELECT Id FROM copado__JobExecution__c];
    }
}