objects/copado__Artifact__c.object
<CustomObject>
    <fields>
        <fullName>copado__Artifact_Repository__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is Repository where the Artifact can be stored, in the master branch</inlineHelpText>
        <label>Package Repository</label>
        <referenceTo>copado__Git_Repository__c</referenceTo>
        <relationshipLabel>Packages</relationshipLabel>
        <relationshipName>Artifacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Artifact_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest Package Version</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>copado__Artifact_Version__c.copado__Artifact__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>copado__Artifact_Version__c</referenceTo>
        <relationshipName>Artifacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__LastJobExecutionId__c</fullName>
        <label>Last Job Execution Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Target_Dev_Hub_Org__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Copado org credential for the dev hub which will be used to create and store the package and its versions</inlineHelpText>
        <label>Target Dev Hub Org</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only dev hub org credentials can be selected. Given value not found or it is not a dev hub org.</errorMessage>
            <filterItems>
                <field>copado__Org__c.copado__is_Developer_Hub_Org__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipName>packageArtifacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Deployment_Flow__c.object
<CustomObject>
    <fields>
        <fullName>copado__Git_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>copado__Git_Repository__c</referenceTo>
        <relationshipName>Deployment_Flows</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Platform__c</fullName>
        <label>Platform</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                    <default>true</default>
                    <label>Salesforce</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>SFDX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Environment__c.object
<CustomObject>
    <fields>
        <fullName>copado__Platform__c</fullName>
        <defaultValue>&quot;Salesforce&quot;</defaultValue>
        <label>Platform</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                    <default>true</default>
                    <label>Salesforce</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PackageVersionUpdateJobTest.cls
@IsTest
private class PackageVersionUpdateJobTest {
    
    @TestSetup
    private static void makeData() {
        User u = TestDataFactory.createUser('Standard User');
        insert u;

        TestDataFactory.assignPermissionSet(u, new Set<String>{ 'Copado_User', 'Copado_Job_Engine' });

        System.runAs(u) {
            TestDataFactory.assignLicense(u.Id, true, true, true, true, true);
        }
    }

    @IsTest
    private static void execute() {
        System.runAs(getRunAsUser()) {
            // Setup

            DataHelper helper = new DataHelper()
                .createRepository('Git Repo')
                .createPipeline('Pipeline 1')
                .createEnvironment('Env 1')
                .addCredential('Cred 1')
                .createPackage('SF_Package')
                .addPackageVersion('Version 1')
                .createJobTemplate('SFDX Package Version Update');

            PackageVersionUpdateJob.Version newVersion = new PackageVersionUpdateJob.Version(
                helper.version.copado__Subscriber_Version_Id__c
            );
            newVersion.installationKey = 'installationKey';

            // Exercise

            copado__JobExecution__c job = new PackageVersionUpdateJob(newVersion).execute();

            // Verify

            copado__Artifact_Version__c version = [
                SELECT copado__LastJobExecutionId__c
                FROM copado__Artifact_Version__c
                WHERE Id = :helper.version.Id
            ];
            System.assertEquals(job.Id, version.copado__LastJobExecutionId__c, 'Job execution should be started.');
        }
    }

    @IsTest
    private static void invalidPackageVersion() {
        System.runAs(getRunAsUser()) {
            // Setup

            Exception e = null;
            PackageVersionUpdateJob.Version newVersion = new PackageVersionUpdateJob.Version(null);
            newVersion.installationKey = 'installationKey';

            // Exercise

            try {
                copado__JobExecution__c job = new PackageVersionUpdateJob(newVersion).execute();
            } catch (Exception ex) {
                e = ex;
            }

            // Verify

            System.assertNotEquals(null, e, 'Exception should be thrown.');
            System.assertEquals(
                'Invalid Subscriber Version Id',
                e.getMessage(),
                'Should throw invalid package version exception.'
            );
        }
    }

    @IsTest
    private static void invalidDevhub() {
        System.runAs(getRunAsUser()) {
            // Setup

            DataHelper helper = new DataHelper()
                .createRepository('Git Repo')
                .createPipeline('Pipeline 1')
                .addCredential('Cred 1')
                .createPackage('SF_Package')
                .addPackageVersion('Version 1')
                .createJobTemplate('SFDX Package Version Update');

            PackageVersionUpdateJob.Version newVersion = new PackageVersionUpdateJob.Version(
                helper.version.copado__Subscriber_Version_Id__c
            );
            newVersion.installationKey = 'installationKey';

            Exception e = null;

            // Exercise

            try {
                copado__JobExecution__c job = new PackageVersionUpdateJob(newVersion).execute();
            } catch (Exception ex) {
                e = ex;
            }

            // Verify

            System.assertNotEquals(null, e, 'Exception should be thrown.');
            System.assertEquals(
                'Could not find Devhub environment.',
                e.getMessage(),
                'Should throw invalid devhub exception.'
            );
        }
    }

    // HELPER

    private class DataHelper {
        private copado__Git_Repository__c repository;
        private copado__Deployment_Flow__c pipeline;
        private copado__Environment__c environment;
        private copado__Org__c credential;
        private copado__Artifact__c pkg;
        private copado__Artifact_Version__c version;
        private copado__JobTemplate__c template;

        private DataHelper createRepository(String name) {
            repository = TestDataFactory.createGitRepository(name);
            insert repository;

            return this;
        }

        private DataHelper createEnvironment(String name) {
            environment = TestDataFactory.createEnvironment(name, 'Production/Developer', 'Salesforce');
            insert environment;

            return this;
        }

        private DataHelper addCredential(String name) {
            credential = TestDataFactory.createCredential(
                name,
                UserInfo.getUserName(),
                environment?.Id,
                environment?.copado__Type__c
            );
            credential.copado__is_Developer_Hub_Org__c = true;
            insert credential;

            return this;
        }

        private DataHelper createPipeline(String name) {
            pipeline = TestDataFactory.createPipeline(name, repository.Id);
            pipeline.copado__Platform__c = 'SFDX';
            insert pipeline;

            return this;
        }

        private DataHelper createPackage(String name) {
            pkg = TestDataFactory.createPackage(name, 'Package_Artifact');
            pkg.copado__Artifact_Repository__c = repository.Id;
            pkg.copado__Target_Dev_Hub_Org__c = credential.Id;
            insert pkg;

            return this;
        }

        @SuppressWarnings('PMD.AvoidHardcodingId')
        private DataHelper addPackageVersion(String name) {
            version = TestDataFactory.createPackageVersion(name, pkg.Id);
            version.copado__Subscriber_Version_Id__c = '04t5g000000UgWxAAK';
            insert version;

            return this;
        }

        private DataHelper createJobTemplate(String name) {
            template = TestDataFactory.createJobTemplate(name);
            insert template;

            return this;
        }
    }

    private static User getRunAsUser() {
        return [
            SELECT Id
            FROM User
            WHERE Profile.Name = 'Standard User' AND UserName LIKE '%testcmcsf@copado.com%'
            LIMIT 1
        ];
    }
}