objects/copado__Deployment_Flow__c.object
<CustomObject>
    <fields>
        <fullName>copado__Git_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>copado__Git_Repository__c</referenceTo>
        <relationshipName>Deployment_Flows</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PipelinesSelector.cls
public with sharing class PipelinesSelector extends fflib_SObjectSelector {
  // CONSTRUCTOR

  public PipelinesSelector() {
    this(true);
  }

  public PipelinesSelector(Boolean enforceFLS) {
    super(false, true, enforceFLS, false);
  }

  // PUBLIC

  public List<SObjectField> getSObjectFieldList() {
    return new List<SObjectField>{
      copado__Deployment_Flow__c.copado__Git_Repository__c
    };
  }

  public SObjectType getSObjectType() {
    return copado__Deployment_Flow__c.sObjectType;
  }

  public List<copado__Deployment_Flow__c> byId(Set<Id> ids) {
    return Database.query(
      newQueryFactory().setCondition('Id IN :ids').toSOQL()
    );
  }
}