objects/copado__Promotion__c.object
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed with errors</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Validation failed</fullName>
                </value>
                <value>
                    <fullName>Merge Conflict</fullName>
                </value>
                <value>
                    <fullName>Conflicts Resolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PromotedUserStories.cls
public with sharing class PromotedUserStories extends fflib_SObjectDomain {
    // CONSTRUCTOR

    public PromotedUserStories(List<copado__Promoted_User_Story__c> records) {
        super(records);
    }

    // PUBLIC

    public override void onAfterInsert() {
        new UpdatePromotionTestLevel(records).execute();
    }

    public override void onAfterUpdate(Map<Id, SObject> old) {
        new UpdatePromotionTestLevel(withStatusChange(records, (Map<Id, copado__Promoted_User_Story__c>) old))
            .execute();
    }

    public override void onAfterDelete() {
        new UpdatePromotionTestLevel(records).execute();
    }

    // PRIVATE

    private Set<Id> withStatusChange(
        List<copado__Promoted_User_Story__c> promotedUserStories,
        Map<Id, copado__Promoted_User_Story__c> old
    ) {
        Set<Id> result = new Set<Id>();

        for (copado__Promoted_User_Story__c ps : promotedUserStories) {
            if (ps.copado__Status__c != old.get(ps.Id).copado__Status__c) {
                result.add(ps.copado__Promotion__c);
            }
        }

        return result;
    }

    // INNER

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> records) {
            return new PromotedUserStories(records);
        }
    }
}