objects/copado__Artifact__c.object
<CustomObject>
    <fields>
        <fullName>copado__Artifact_Repository__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is Repository where the Artifact can be stored, in the master branch</inlineHelpText>
        <label>Package Repository</label>
        <referenceTo>copado__Git_Repository__c</referenceTo>
        <relationshipLabel>Packages</relationshipLabel>
        <relationshipName>Artifacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Artifact_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest Package Version</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>copado__Artifact_Version__c.copado__Artifact__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>copado__Artifact_Version__c</referenceTo>
        <relationshipName>Artifacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Target_Dev_Hub_Org__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Copado org credential for the dev hub which will be used to create and store the package and its versions</inlineHelpText>
        <label>Target Dev Hub Org</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only dev hub org credentials can be selected. Given value not found or it is not a dev hub org.</errorMessage>
            <filterItems>
                <field>copado__Org__c.copado__is_Developer_Hub_Org__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipName>packageArtifacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Environment__c.object
<CustomObject>
    <fields>
        <fullName>copado__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__JobStep__c.object
<CustomObject>
    <fields>
        <fullName>copado__ConfigJson__c</fullName>
        <label>ConfigJson</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>copado__ExecutionSequence__c</fullName>
        <description>Used to define the order of execution in the context of User Story Deployment</description>
        <label>Execution Sequence</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>before</fullName>
                    <label>Before Deployment</label>
                </value>
                <value>
                    <fullName>after</fullName>
                    <label>After Deployment</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Git_Repository__c</fullName>
        <formula>BLANKVALUE(
    copado__JobExecution__r.copado__Snapshot__r.copado__Git_Repository__c, 
    BLANKVALUE(
        copado__JobExecution__r.copado__Pipeline__r.copado__Git_Repository__c,
        BLANKVALUE(
            copado__JobExecution__r.copado__Promotion__r.copado__Project__r.copado__Deployment_Flow__r.copado__Git_Repository__c, 
            copado__JobExecution__r.copado__Deployment__r.copado__Promotion__r.copado__Project__r.copado__Deployment_Flow__r.copado__Git_Repository__c
        )
    )
)</formula>
        <label>Git Repository</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Order__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>copado__Type__c</fullName>
        <description>Defines the behaviour this step will have when executed.</description>
        <inlineHelpText>Defines the behaviour this step will have when executed.</inlineHelpText>
        <label>Behaviour</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Function</fullName>
                </value>
                <value>
                    <fullName>Flow</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__UserStory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>copado__User_Story__c</referenceTo>
        <relationshipLabel>Deployment Steps</relationshipLabel>
        <relationshipName>JobSteps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>copado__Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Credential.</description>
        <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Credential.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Git_Repository__c</fullName>
        <formula>copado__Project__r.copado__Deployment_Flow__r.copado__Git_Repository__c</formula>
        <label>Git Repository</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Order__c</fullName>
        <label>Order</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>copado__User_Story_Title__c</fullName>
        <description>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</description>
        <inlineHelpText>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</inlineHelpText>
        <label>User Story Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ConfigurePipelineDistributionStepTest.cls
@IsTest
private class ConfigurePipelineDistributionStepTest {

    @TestSetup
    private static void makeData() {
        TestUtilities.setup();
        System.runAs(TestUtilities.getRunAsUser()) {
            createData();
        }
    }

    @IsTest
    private static void createDeploymentStepForNewStory() {
        System.runAs(TestUtilities.getRunAsUser()) {

            // Setup

            copado__Artifact_Version__c version = getVersion();

            ConfigurePipelineDistributionStep.Request request = new ConfigurePipelineDistributionStep.Request();
            request.newSerializedUserStory = '{"copado__User_Story_Title__c": "Install PackageTest - 1.0.0.0"}';
            request.packageVersionId = version.Id;

            // Exercise

            ConfigurePipelineDistributionStep.Result result = ConfigurePipelineDistributionStep.createDeploymentStep(
                    new List<ConfigurePipelineDistributionStep.Request>{ request }
                )
                .get(0);

            // Verify

            List<copado__User_Story__c> story = getUserStoryWithSteps();

            System.assertEquals(1, story.size(), 'New user story should be created.');
            System.assertEquals(result.userStoryId, story[0].Id, 'Result should contain new user story.');
            System.assertEquals(1, story[0].copado__JobSteps__r.size(), 'New deployment step should be created for user story.');

            copado__JobStep__c step = story[0].copado__JobSteps__r[0];
            System.assertEquals(1, step.copado__Order__c, 'Order of step should be 1.');
            System.assertEquals('Start Pkg - 1.0.0.0 Installation Job', step.Name, 'Step name should be correct.');

            ConfigurePipelineDistributionStep.ConfigJson configJson = (ConfigurePipelineDistributionStep.ConfigJson) JSON.deserialize(
                step.copado__ConfigJson__c,
                ConfigurePipelineDistributionStep.ConfigJson.class
            );
            System.assertEquals(2, configJson.parameters.size(), 'Step name should be correct.');
            System.assert(configJson.flowName.contains('InitiatePipelineDistribution'), 'Step name should be correct.');
            
            List<ConfigurePipelineDistributionStep.Parameter> params = new List<ConfigurePipelineDistributionStep.Parameter>{
                new ConfigurePipelineDistributionStep.Parameter('packageVersionId', version.Id),
                new ConfigurePipelineDistributionStep.Parameter('deploymentId', '{$Job.ExecutionParent.Id}')
            };
            System.assertEquals(params.toString(), configJson.parameters.toString(), 'Parameters should be correct.');
        }
    }


    @IsTest
    private static void createDeploymentStepForExistingStory() {
        System.runAs(TestUtilities.getRunAsUser()) {

            // Setup

            copado__User_Story__c us = TestDataFactory.createUserStory('US', 'Draft', null, null, null, null);
            insert us;

            insert new copado__JobStep__c(
                Name = 'Step 1',
                copado__UserStory__c = us.Id,
                copado__ExecutionSequence__c = 'after',
                copado__Order__c = 1,
                copado__Type__c = 'Flow'
            );

            ConfigurePipelineDistributionStep.Request request = new ConfigurePipelineDistributionStep.Request();
            request.existingUserStoryId = us.Id;
            request.packageVersionId = getVersion().Id;

            // Exercise

            ConfigurePipelineDistributionStep.Result result = ConfigurePipelineDistributionStep.createDeploymentStep(
                    new List<ConfigurePipelineDistributionStep.Request>{ request }
                )
                .get(0);

            // Verify

            List<copado__User_Story__c> story = getUserStoryWithSteps();

            System.assertEquals(1, story.size(), 'Only existing user story should be present.');
            System.assertEquals(result.userStoryId, story[0].Id, 'Result should contain existing user story.');
            System.assertEquals(2, story[0].copado__JobSteps__r.size(), 'New deployment step should be created for user story.');
            System.assertEquals(2, story[0].copado__JobSteps__r[0].copado__Order__c, 'Order of step should be 2.');
        }
    }

    // HELPER

    private static void createData() {
        copado__Git_Repository__c repository = TestDataFactory.createGitRepository('Repo');
        insert repository;

        copado__Environment__c environment = TestDataFactory.createEnvironment('Env', 'Production/Developer', 'SFDX');
        insert environment;

        copado__Org__c credential = TestDataFactory.createCredential(
            'Cred',
            UserInfo.getUserName(),
            environment.Id,
            'Production/Developer'
        );
        credential.copado__is_Developer_Hub_Org__c = true;
        insert credential;

        copado__Artifact__c pkg = TestDataFactory.createPackage('Pkg', 'Package_Artifact');
        pkg.copado__Artifact_Repository__c = repository.Id;
        pkg.copado__Target_Dev_Hub_Org__c = credential.Id;
        insert pkg;

        copado__Artifact_Version__c version = TestDataFactory.createPackageVersion('Pkg V1', pkg.Id);
        version.copado__Version_number__c = '1.0.0.0';
        insert version;
    }


    private static List<copado__User_Story__c> getUserStoryWithSteps() {
        return [
            SELECT
                Id,
                (
                    SELECT Name, copado__ConfigJson__c, copado__Order__c
                    FROM copado__JobSteps__r
                    ORDER BY copado__Order__c DESC
                )
            FROM copado__User_Story__c
        ];
    }

    private static copado__Artifact_Version__c getVersion() {
        return [SELECT Id FROM copado__Artifact_Version__c LIMIT 1];
    }
}