objects/copado__Artifact__c.object
<CustomObject>
    <fields>
        <fullName>copado__Artifact_Repository__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is Repository where the Artifact can be stored, in the master branch</inlineHelpText>
        <label>Package Repository</label>
        <referenceTo>copado__Git_Repository__c</referenceTo>
        <relationshipLabel>Packages</relationshipLabel>
        <relationshipName>Artifacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Artifact_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest Package Version</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>copado__Artifact_Version__c.copado__Artifact__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>copado__Artifact_Version__c</referenceTo>
        <relationshipName>Artifacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Package_Id__c</fullName>
        <inlineHelpText>Related package identifier. Being used as a Package Id for package version creation and also in use into the sfdx-project.json file as a package alias.</inlineHelpText>
        <label>Package Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Package_Type__c</fullName>
        <inlineHelpText>For detailed information : https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_dev2gp_plan_pkg_types.htm</inlineHelpText>
        <label>Package Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unlocked</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Second-Generation Package</fullName>
                </value>
                <value>
                    <fullName>First-Generation Package</fullName>
                </value>
                <value>
                    <fullName>Unmanaged</fullName>
                    <isActive>false</isActive>
                    <label>Unmanaged</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Environment__c.object
<CustomObject>
    <fields>
        <fullName>copado__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__JobStep__c.object
<CustomObject>
    <fields>
        <fullName>copado__Git_Repository__c</fullName>
        <formula>BLANKVALUE(
    copado__JobExecution__r.copado__Snapshot__r.copado__Git_Repository__c, 
    BLANKVALUE(
        copado__JobExecution__r.copado__Pipeline__r.copado__Git_Repository__c,
        BLANKVALUE(
            copado__JobExecution__r.copado__Promotion__r.copado__Project__r.copado__Deployment_Flow__r.copado__Git_Repository__c, 
            copado__JobExecution__r.copado__Deployment__r.copado__Promotion__r.copado__Project__r.copado__Deployment_Flow__r.copado__Git_Repository__c
        )
    )
)</formula>
        <label>Git Repository</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__JobExecution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Job Execution</label>
        <referenceTo>copado__JobExecution__c</referenceTo>
        <relationshipLabel>Job Steps</relationshipLabel>
        <relationshipName>JobSteps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__JobTemplate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Job Template</label>
        <referenceTo>copado__JobTemplate__c</referenceTo>
        <relationshipLabel>Job Steps</relationshipLabel>
        <relationshipName>JobSteps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Result__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Last Result</label>
        <referenceTo>copado__Result__c</referenceTo>
        <relationshipLabel>Job Steps</relationshipLabel>
        <relationshipName>JobSteps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Type__c</fullName>
        <description>Defines the behaviour this step will have when executed.</description>
        <inlineHelpText>Defines the behaviour this step will have when executed.</inlineHelpText>
        <label>Behaviour</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Function</fullName>
                </value>
                <value>
                    <fullName>Flow</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Result__c.object
<CustomObject>
    <fields>
        <fullName>copado__JobStep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>When this result is the outcome of a Job Step, that is executed as part of a Job Template, this fields points to the Job Step. (note that Job Step and Function can be populated at the same time)</inlineHelpText>
        <label>Job Step</label>
        <referenceTo>copado__JobStep__c</referenceTo>
        <relationshipLabel>Results</relationshipLabel>
        <relationshipName>Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Job_Type__c</fullName>
        <inlineHelpText>API name of the parent Job. Used for reporting purposes mainly.</inlineHelpText>
        <label>Job API Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Integration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Result_Data__c</fullName>
        <inlineHelpText>Includes all the returned data by the process. This can be used by other processes.</inlineHelpText>
        <label>Result Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PackageVersionInstallationKey__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores Package version installation keys</description>
    <fields>
        <fullName>InstallationKey__c</fullName>
        <label>Installation Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Package Version Installation Key</label>
</CustomObject>

classes/PackageVersionCreateFlowTest.cls
@IsTest
private class PackageVersionCreateFlowTest {
    @TestSetup
    private static void setUp() {
        TestUtilities.setup();
    }

    @IsTest
    private static void createPackageVersion() {
        // Setup

        System.runAs(TestUtilities.getRunAsUser()) {
            copado__Environment__c environment = TestDataFactory.createEnvironment(
                'DevHub',
                'Production/Developer',
                'SFDX'
            );
            insert environment;

            copado__Org__c credential = TestDataFactory.createCredential(
                'DevHub',
                'test@test.com',
                environment.Id,
                'Production/Developer'
            );
            insert credential;

            copado__JobTemplate__c template = TestDataFactory.createJobTemplate(
                'SFDX Package Import'
            );
            insert template;

            copado__JobExecution__c execution = createJobExecution(template, environment);

            copado__Artifact__c pkg = createPackage(createRepository());
            
            copado__Result__c result = createResult(
                createJobStep('Create Package', execution.Id).Id,
                JSON.serialize(createVersion(pkg))
            );

            Map<String, Object> flowParams = getFlowParams(result.Id);

            // Exercise
            Test.startTest();
            new Flow.Interview.CreatePackageVersion(flowParams).start();
            Test.stopTest();

            // Verify
                       
            system.assertEquals(
                getResult(result?.Id).copado__Result_Data__c, 
                JSON.serialize(createVersion(pkg)),
                'Package version details not updated'
            );
            system.assertEquals(
                getInstallationkey()[0].InstallationKey__c,
                'test1234',
                'Insallation key updation failed'
            );
        }
    }

    private static copado__Git_Repository__c createRepository() {
        copado__Git_Repository__c repo = new copado__Git_Repository__c(Name = 'My Repo');
        insert repo;
        return repo;
    }

    private static Map<String, Object> getFlowParams(Id resultId) {
        Map<String, Object> flowParams = new Map<String, Object>{
            'packageVersionJson' => '{"Package2Id":"0Ho5g00000000VzCAI","Branch":null,"Tag":null,"MajorVersion":0,"MinorVersion":1,"PatchVersion":0,"BuildNumber":1,"Id":"05i5g00000000OcAAI","SubscriberPackageVersionId":"04t5g000000xwXMAAY","Name":"ver 0.1","NamespacePrefix":null,"Package2Name":"Testpkg","Description":null,"Version":"0.1.0.1","IsPasswordProtected":false,"IsReleased":false,"CreatedDate":"2021-09-01 11:42","LastModifiedDate":"2021-09-01 11:42","InstallUrl":"https://login.salesforce.com/packaging/installPackage.apexp?p0=04t5g000000xwXMAAY","CodeCoverage":"","ValidationSkipped":false,"AncestorId":"N/A","AncestorVersion":"N/A","Alias":""}',
            'resultId' => resultId,
            'jsonInformation' => '{\"name\":\"testversion\",\"path\":\"force-app\",\"versionnumber\":\"\",\"branch\":\"master\",\"installationkeybypass\":false,\"installationkey\":\"test1234\",\"versiondescription\":\"\",\"package\":\"a0509000003waC9AAI\"}'
        };
        return flowParams;
    }

    @SuppressWarnings('PMD.AvoidHardcodingId')
    private static copado__Artifact__c createPackage(Copado__Git_Repository__c repo) {
        copado__Artifact__c pkg = new copado__Artifact__c(
            Name = 'Testpkg',
            copado__Package_Type__c = 'Unlocked',
            copado__Artifact_Repository__c = repo.Id,
            copado__Package_Id__c = '0Ho5g00000000VzCAI',
            RecordTypeId = SObjectType.copado__Artifact__c.getRecordTypeInfosByDeveloperName()
                .get('Package_Artifact')
                .getRecordTypeId()
        );
        insert pkg;

        return pkg;
    }

    private static copado__JobExecution__c createJobExecution(
        copado__JobTemplate__c template,
        copado__Environment__c environment
    ) {
        copado__JobExecution__c execution = new copado__JobExecution__c(
            copado__Template__c = template.Id,
            copado__Destination__c = environment.Id
        );
        insert execution;

        return execution;
    }

    private static copado__JobStep__c createJobStep(String name, Id executionId) {
        copado__JobStep__c step = new copado__JobStep__c(
            Name = name,
            copado__JobExecution__c = executionId,
            copado__Type__c = 'Flow'
        );
        insert step;

        return step;
    }

    private static copado__Result__c createResult(Id stepId, String version) {
        copado__Result__c result = new copado__Result__c(
            copado__JobStep__c = stepId,
            copado__Result_Data__c = version,
            copado__Job_Type__c = 'Integration'
        );
        insert result;
        
        return result;
    }
    
    private static copado__Artifact_Version__c createVersion(copado__Artifact__c pkg) {
        String dataJSON = '{\"uninstallscript\":null,\"postinstallscript\":null,\"postinstallurl\":null,\"releasenotesurl\":null,\"skipvalidation\":null,\"codecoverage\":null,\"installationkeybypass\":false,\"tag\":null,\"overrideProjectJsonPath\":null,\"overridePath\":null,\"apiversion\":\"45.0\"}';

        copado__Artifact_Version__c result = new copado__Artifact_Version__c();
        result.copado__Artifact__c = pkg.Id;
        result.copado__Package_Version_Id__c = '05i5g00000000OcAAI';
        result.copado__Subscriber_Version_Id__c = '04t5g000000xwXMAAY';
        result.copado__Is_released__c = false;
        result.copado__Branch__c = null;
        result.copado__Version_Name__c = 'ver 0.1';
        result.copado__Tag__c = null;
        result.copado__Version_Description__c = null;
        result.copado__Version_number__c = '0.1.0.1';
        result.copado__Data_JSON__c = dataJSON;
        result.Name = pkg.Name + ' - ' + '0.1.0.1';
        
        return result;
    }

    private static copado__Result__c getResult(Id resultId) {
        return [SELECT copado__Result_Data__c FROM copado__Result__c WHERE Id = :resultId];
    }

    private static List<PackageVersionInstallationKey__c> getInstallationkey() {
        return [SELECT InstallationKey__c FROM PackageVersionInstallationKey__c];
    }
}