objects/copado__Artifact__c.object
<CustomObject>
    <fields>
        <fullName>IsOrgDependent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Org Dependent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__LastJobExecutionId__c</fullName>
        <label>Last Job Execution Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__No_Namespace__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Enables the package creation with no namespace; available only for unlocked packages.</inlineHelpText>
        <label>No Namespace</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__Package_Type__c</fullName>
        <inlineHelpText>For detailed information : https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_dev2gp_plan_pkg_types.htm</inlineHelpText>
        <label>Package Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unlocked</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Second-Generation Package</fullName>
                </value>
                <value>
                    <fullName>First-Generation Package</fullName>
                </value>
                <value>
                    <fullName>Unmanaged</fullName>
                    <isActive>false</isActive>
                    <label>Unmanaged</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Source_Api_Version__c</fullName>
        <inlineHelpText>The API version that the source of your package is compatible with. This field is important if you’re using a metadata type that has changed in a recent salesforce release.</inlineHelpText>
        <label>Source Api Version</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1.0</fullName>
                </value>
                <value>
                    <fullName>2.0</fullName>
                </value>
                <value>
                    <fullName>3.0</fullName>
                </value>
                <value>
                    <fullName>4.0</fullName>
                </value>
                <value>
                    <fullName>5.0</fullName>
                </value>
                <value>
                    <fullName>6.0</fullName>
                </value>
                <value>
                    <fullName>7.0</fullName>
                </value>
                <value>
                    <fullName>8.0</fullName>
                </value>
                <value>
                    <fullName>9.0</fullName>
                </value>
                <value>
                    <fullName>10.0</fullName>
                </value>
                <value>
                    <fullName>11.0</fullName>
                </value>
                <value>
                    <fullName>12.0</fullName>
                </value>
                <value>
                    <fullName>13.0</fullName>
                </value>
                <value>
                    <fullName>14.0</fullName>
                </value>
                <value>
                    <fullName>15.0</fullName>
                </value>
                <value>
                    <fullName>16.0</fullName>
                </value>
                <value>
                    <fullName>17.0</fullName>
                </value>
                <value>
                    <fullName>18.0</fullName>
                </value>
                <value>
                    <fullName>19.0</fullName>
                </value>
                <value>
                    <fullName>20.0</fullName>
                </value>
                <value>
                    <fullName>21.0</fullName>
                </value>
                <value>
                    <fullName>22.0</fullName>
                </value>
                <value>
                    <fullName>23.0</fullName>
                </value>
                <value>
                    <fullName>24.0</fullName>
                </value>
                <value>
                    <fullName>25.0</fullName>
                </value>
                <value>
                    <fullName>26.0</fullName>
                </value>
                <value>
                    <fullName>27.0</fullName>
                </value>
                <value>
                    <fullName>28.0</fullName>
                </value>
                <value>
                    <fullName>29.0</fullName>
                </value>
                <value>
                    <fullName>30.0</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Target_Dev_Hub_Org__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Copado org credential for the dev hub which will be used to create and store the package and its versions</inlineHelpText>
        <label>Target Dev Hub Org</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only dev hub org credentials can be selected. Given value not found or it is not a dev hub org.</errorMessage>
            <filterItems>
                <field>copado__Org__c.copado__is_Developer_Hub_Org__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipName>packageArtifacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PackageCreateHandler.cls
public with sharing class PackageCreateHandler {
    @AuraEnabled
    public static void startCreate(Id recordId) {
        Map<String, Object> jsonInformation = getPackageInfo(recordId);

        List<Copado.PackageCreateAction.Response> response = Copado.PackageCreateAction.create(
            new List<Copado.PackageCreateAction.Request>{
                new Copado.PackageCreateAction.Request(recordId, JSON.serialize(jsonInformation))
            }
        );

        update Security.stripInaccessible(
                AccessType.UPDATABLE,
                new List<copado__Artifact__c>{
                    new copado__Artifact__c(
                        Id = recordId,
                        copado__LastJobExecutionId__c = response[0]?.job?.Id
                    )
                }
            )
            .getRecords();
    }

    private static Map<String, Object> getPackageInfo(Id recordId) {
        copado__Artifact__c pkg = new PackagesSelector().byIds(new Set<Id>{ recordId })?.get(0);

        Map<String, Object> result = new Map<String, Object>();
        result.put('apiversion', pkg?.copado__Source_Api_Version__c);
        result.put('packagetype', pkg?.copado__Package_Type__c);
        result.put('nonamespace', pkg?.copado__No_Namespace__c);
        result.put('orgdependent', pkg?.IsOrgDependent__c);
        result.put('devhub', pkg?.copado__Target_Dev_Hub_Org__c);
   
        return result;     
}

}