objects/copado__Deployment_Flow__c.object
<CustomObject>
    <fields>
        <fullName>copado__Git_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>copado__Git_Repository__c</referenceTo>
        <relationshipName>Deployment_Flows</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Platform__c</fullName>
        <label>Platform</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                    <default>true</default>
                    <label>Salesforce</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>SFDX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Promotion_Job_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion Job Template</label>
        <referenceTo>copado__JobTemplate__c</referenceTo>
        <relationshipLabel>Pipelines</relationshipLabel>
        <relationshipName>Pipelines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Environment__c.object
<CustomObject>
    <fields>
        <fullName>copado__Platform__c</fullName>
        <defaultValue>&quot;Salesforce&quot;</defaultValue>
        <label>Platform</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                    <default>true</default>
                    <label>Salesforce</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Run_all_tests__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If selected, &quot;Run all local tests&quot; will be enforced when deploying to this environment.</inlineHelpText>
        <label>Run all local tests</label>
        <type>Checkbox</type>
    </fields>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Promotion__c.object
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <fields>
        <fullName>Apex_Test_Level__c</fullName>
        <description>Test levels in order from least to most restrictive</description>
        <label>Apex Test Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Apex_Test_Level</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Destination_Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Destination Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>Promotions (Destination Environment)</relationshipLabel>
        <relationshipName>Promotions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Destination_Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The destination credential that will be used when creating the deployment. This credential is auto-populated based on the pipeline linked to the project.</inlineHelpText>
        <label>Destination Credential</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>copado__Org__c.copado__Environment__c</field>
                <operation>equals</operation>
                <valueField>$Source.copado__Destination_Environment__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>Promotions (Destination Credential)</relationshipLabel>
        <relationshipName>Promotions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Platform__c</fullName>
        <formula>IF( NOT(ISBLANK( copado__Project__c )) ,  TEXT(copado__Project__r.copado__Deployment_Flow__r.copado__Platform__c) ,  IF( NOT(ISBLANK( copado__Release__c )),  TEXT(copado__Release__r.copado__Project__r.copado__Deployment_Flow__r.copado__Platform__c) , &apos;Salesforce&apos;) )</formula>
        <inlineHelpText>This field auto-populates and displays the pipeline platform.</inlineHelpText>
        <label>Platform</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select a project linked to an active pipeline.</inlineHelpText>
        <label>Project</label>
        <referenceTo>copado__Project__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Source_Environment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Source Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Source_Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The source credential that will be used when creating the deployment. This credential is auto-populated based on the pipeline linked to the project.</inlineHelpText>
        <label>Source Credential</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>copado__Org__c.copado__Environment__c</field>
                <operation>equals</operation>
                <valueField>$Source.copado__Source_Environment__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>Promotions (Source Credential)</relationshipLabel>
        <relationshipName>Promotions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed with errors</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Validation failed</fullName>
                </value>
                <value>
                    <fullName>Merge Conflict</fullName>
                </value>
                <value>
                    <fullName>Conflicts Resolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Apex_Test_Level__c</fullName>
        <description>Test levels in order from least to most restrictive</description>
        <label>Apex Test Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Apex_Test_Level</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Credential.</description>
        <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Credential.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Git_Repository__c</fullName>
        <formula>copado__Project__r.copado__Deployment_Flow__r.copado__Git_Repository__c</formula>
        <label>Git Repository</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</description>
        <inlineHelpText>Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</inlineHelpText>
        <label>Credential</label>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>User Stories (Credential)</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Platform__c</fullName>
        <description>This field auto-populates and displays the pipeline platform</description>
        <formula>BLANKVALUE( 
    TEXT(copado__Project__r.copado__Deployment_Flow__r.copado__Platform__c) ,  
    BLANKVALUE(  
        TEXT(copado__Release__r.copado__Project__r.copado__Deployment_Flow__r.copado__Platform__c), 
        &apos;&apos;
    ) 
)</formula>
        <inlineHelpText>This field auto-populates and displays the pipeline platform</inlineHelpText>
        <label>Platform</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project where the User Story belongs.</description>
        <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
        <label>Project</label>
        <referenceTo>copado__Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Apex_Test_Level.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>No Test Run</fullName>
        <default>true</default>
        <label>No Test Run</label>
    </customValue>
    <customValue>
        <fullName>Run Specified Tests</fullName>
    </customValue>
    <customValue>
        <fullName>Run Local Tests</fullName>
    </customValue>
    <customValue>
        <fullName>Run All Tests In Org</fullName>
    </customValue>
    <customValue>
        <fullName>Run All Tests</fullName>
        <isActive>false</isActive>
        <label>Run All Tests</label>
    </customValue>
    <description>Test levels in order from least to most restrictive</description>
    <masterLabel>Apex Test Level</masterLabel>
</GlobalValueSet>

classes/UpdatePromotionTestLevelTest.cls
@IsTest
private class UpdatePromotionTestLevelTest {
    @IsTest
    private static void onInsert() {
        System.runAs(getRunAsUser()) {
            // Setup

            createData('SFDX');

            // Exercise

            List<copado__Promoted_User_Story__c> ps = addStoriesToPromotionWithLevels(
                new Set<String>{ 'Run Local Tests', 'Run Specified Tests', 'No Test Run' }
            );

            // Verify

            copado__Promotion__c p = promotion(ps[0].copado__Promotion__c);
            System.assertEquals('Run Local Tests', p.Apex_Test_Level__c, 'Test Levels are incorrect.');
        }
    }

    @IsTest
    private static void onDelete() {
        System.runAs(getRunAsUser()) {
            // Setup

            createData('SFDX');

            List<copado__Promoted_User_Story__c> ps = addStoriesToPromotionWithLevels(
                new Set<String>{ 'Run Local Tests', 'Run Specified Tests', 'No Test Run' }
            );

            // Exercise

            copado__Promoted_User_Story__c toDelete = byStoryTestLevel('Run Local Tests');
            delete toDelete;

            // Verify

            copado__Promotion__c p = promotion(ps[0].copado__Promotion__c);
            System.assertEquals('Run Specified Tests', p.Apex_Test_Level__c, 'Test Levels are incorrect.');
        }
    }

    @IsTest
    private static void onUpdate() {
        System.runAs(getRunAsUser()) {
            // Setup

            createData('SFDX');

            List<copado__Promoted_User_Story__c> ps = addStoriesToPromotionWithLevels(
                new Set<String>{ 'Run Local Tests', 'Run Specified Tests', 'No Test Run' }
            );

            // Exercise

            copado__Promoted_User_Story__c toUpdate = byStoryTestLevel('Run Local Tests');
            toUpdate.copado__Status__c = 'Outdated';
            update toUpdate;

            // Verify

            copado__Promotion__c p = promotion(ps[0].copado__Promotion__c);
            System.assertEquals('Run Specified Tests', p.Apex_Test_Level__c, 'Test Levels are incorrect.');
        }
    }

    @IsTest
    private static void onInsertWithRunAllTestEnv() {
        System.runAs(getRunAsUser()) {
            // Setup

            createData('SFDX');
            setRunAllTestAsTrue();

            // Exercise

            List<copado__Promoted_User_Story__c> ps = addStoriesToPromotionWithLevels(
                new Set<String>{ 'Run Specified Tests', 'No Test Run' }
            );

            // Verify

            copado__Promotion__c p = promotion(ps[0].copado__Promotion__c);
            System.assertEquals('Run All Tests In Org', p.Apex_Test_Level__c, 'Test Levels should not change.');
        }
    }

    @IsTest
    private static void onDeleteWithRunAllTestEnv() {
        System.runAs(getRunAsUser()) {
            // Setup

            createData('SFDX');
            setRunAllTestAsTrue();

            List<copado__Promoted_User_Story__c> ps = addStoriesToPromotionWithLevels(
                new Set<String>{ 'Run All Tests In Org', 'Run Specified Tests' }
            );

            // Exercise

            copado__Promoted_User_Story__c toDelete = byStoryTestLevel('Run All Tests In Org');
            delete toDelete;

            // Verify

            copado__Promotion__c p = promotion(ps[0].copado__Promotion__c);
            System.assertEquals('Run All Tests In Org', p.Apex_Test_Level__c, 'Test Levels should not change.');
        }
    }

    @IsTest
    private static void onUpdateWithRunAllTestEnv() {
        System.runAs(getRunAsUser()) {
            // Setup

            createData('SFDX');
            setRunAllTestAsTrue();

            List<copado__Promoted_User_Story__c> ps = addStoriesToPromotionWithLevels(
                new Set<String>{ 'Run All Tests In Org', 'No Test Run' }
            );

            // Exercise

            copado__Promoted_User_Story__c toUpdate = byStoryTestLevel('Run All Tests In Org');
            toUpdate.copado__Status__c = 'Outdated';
            update toUpdate;

            // Verify

            copado__Promotion__c p = promotion(ps[0].copado__Promotion__c);
            System.assertEquals('Run All Tests In Org', p.Apex_Test_Level__c, 'Test Levels should not change.');
        }
    }

    @IsTest
    private static void onAllUpdateToOutdated() {
        System.runAs(getRunAsUser()) {
            // Setup

            createData('SFDX');

            List<copado__Promoted_User_Story__c> ps = addStoriesToPromotionWithLevels(
                new Set<String>{ 'Run All Tests In Org', 'Run Specified Tests', 'No Test Run' }
            );

            // Exercise

            ps[0].copado__Status__c = 'Outdated';
            ps[1].copado__Status__c = 'Outdated';
            ps[2].copado__Status__c = 'Outdated';
            update ps;

            // Verify

            copado__Promotion__c p = promotion(ps[0].copado__Promotion__c);
            System.assertEquals('Run All Tests In Org', p.Apex_Test_Level__c, 'Test Levels should not change.');
        }
    }

    @IsTest
    private static void forOtherPlatform() {
        System.runAs(getRunAsUser()) {
            // Setup

            createData('Salesforce');

            // Exercise

            List<copado__Promoted_User_Story__c> ps = addStoriesToPromotionWithLevels(
                new Set<String>{ 'Run All Tests In Org', 'Run Specified Tests', 'No Test Run' }
            );

            // Verify

            copado__Promotion__c p = promotion(ps[0].copado__Promotion__c);
            System.assertEquals('No Test Run', p.Apex_Test_Level__c, 'Test Levels should not update.');
        }
    }

    // HELPER

    @TestSetup
    private static void setup() {
        User u = TestDataFactory.createUser('Standard User');
        insert u;

        TestDataFactory.assignPermissionSet(u, new Set<String>{ 'Copado_User', 'Copado_Job_Engine', 'CMC_SFDX_Admin' });

        System.runAs(u) {
            TestDataFactory.assignLicense(u.Id, true, true, true, true, true);
        }
    }

    private static void createData(String platform) {
        copado__Git_Repository__c repo = TestDataFactory.createGitRepository('Repo 1');
        insert repo;

        copado__Environment__c sEnv = TestDataFactory.createEnvironment('Src', 'Production/Developer', platform);
        copado__Environment__c dEnv = TestDataFactory.createEnvironment('Dst', 'Production/Developer', platform);
        insert new List<copado__Environment__c>{ sEnv, dEnv };

        copado__Org__c sCred = TestDataFactory.createCredential('Src', UserInfo.getUserName(), sEnv.Id, null);
        copado__Org__c dCred = TestDataFactory.createCredential('Dst', UserInfo.getUserName(), dEnv.Id, null);
        insert new List<copado__Org__c>{ sCred, dCred };

        copado__JobTemplate__c promotionJob = TestDataFactory.createJobTemplate('Promotion');
        insert promotionJob;

        copado__Deployment_Flow__c pipeline = TestDataFactory.createPipeline('Pipeline1', repo.Id);
        pipeline.copado__Platform__c = platform;
        pipeline.copado__Promotion_Job_Template__c = promotionJob.Id;
        insert pipeline;

        copado__Deployment_Flow_Step__c pipelineConnection = TestDataFactory.createPipelineConnection(
            pipeline.Id,
            sEnv.Id,
            dEnv.Id
        );
        insert pipelineConnection;

        copado__Project__c project = TestDataFactory.createProject('Project 1', pipeline.Id);
        insert project;

        List<copado__User_Story__c> stories = new List<copado__User_Story__c>();

        for (String testLevel : UpdatePromotionTestLevel.TEST_LEVELS_IN_ORDER) {
            stories.add(
                new copado__User_Story__c(
                    copado__Project__c = project.Id,
                    copado__Org_Credential__c = sCred.Id,
                    Apex_Test_Level__c = testLevel
                )
            );
        }

        insert stories;

        insert new copado__Promotion__c(
            copado__Project__c = project.Id,
            copado__Source_Environment__c = sEnv.Id,
            copado__Source_Org_Credential__c = sCred.Id,
            copado__Destination_Environment__c = dEnv.Id,
            copado__Destination_Org_Credential__c = dCred.Id
        );
    }

    private static List<copado__Promoted_User_Story__c> addStoriesToPromotionWithLevels(Set<String> testLevels) {
        List<copado__Promoted_User_Story__c> ps = new List<copado__Promoted_User_Story__c>();

        copado__Promotion__c promotion = [SELECT Id FROM copado__Promotion__c LIMIT 1];

        for (copado__User_Story__c story : [
            SELECT Id
            FROM copado__User_Story__c
            WHERE Apex_Test_Level__c IN :testLevels
        ]) {
            ps.add(
                new copado__Promoted_User_Story__c(
                    copado__Promotion__c = promotion.Id,
                    copado__User_Story__c = story.Id
                )
            );
        }

        insert ps;
        return ps;
    }

    private static copado__Promotion__c promotion(Id pId) {
        return [SELECT Apex_Test_Level__c FROM copado__Promotion__c WHERE Id = :pId LIMIT 1];
    }

    private static copado__Promoted_User_Story__c byStoryTestLevel(String testLevel) {
        return [
            SELECT Id
            FROM copado__Promoted_User_Story__c
            WHERE copado__User_Story__r.Apex_Test_Level__c = :testLevel
            LIMIT 1
        ];
    }

    private static void setRunAllTestAsTrue() {
        copado__Environment__c dEnv = [SELECT Id FROM copado__Environment__c WHERE Name = 'Dst' LIMIT 1];
        dEnv.copado__Run_all_tests__c = true;
        update dEnv;
    }

    private static User getRunAsUser() {
        return [
            SELECT Id
            FROM User
            WHERE Profile.Name = 'Standard User' AND UserName LIKE '%testcmcsf@copado.com%'
            LIMIT 1
        ];
    }
}